### ISSUE TITLE
.dropify().destroy()?

### ISSUE THREAD

**Issue by heberda** [JeremyFagis/dropify#15]
It would be quite handy to destroy dropify.

I have turned `dropify` on for a specific class (.dropify). If a new element is created with the same class and I call `dropify` again I will end up with two `dropify` elements on any objects which already existed.

Would be handy to remove them or at least have a check method? for example, `isDropified()`?

**Comment by JeremyFagis** [comment]
Thanks for the feedback. :+1: Really good advice, I have to check if it's already "dropified". I'll work on it soon!

**Comment by heberda** [comment]
Awesome, nice uploader by the way :)

**Comment by JeremyFagis** [comment]
Fixed in #23.
