### ISSUE TITLE
Huge images on touch devices

### ISSUE THREAD

**Issue by heberda** [JeremyFagis/dropify#16]
I came across a rather fun issue today. When `isTouchDevice()` returns true it seems the image loads full size. This forces all content off the page. 

From what I can see this is caused by a combination of `height:auto!important` and `display:block`. To help you debug, the issue was found on a touch screen laptop. I have also found the issue occurs using chrome's device emulator.

**Comment by JeremyFagis** [comment]
Fixed in #23.
