### ISSUE TITLE
Example of isDropified() init() and destroy()

### ISSUE THREAD

**Issue by galipmedia** [JeremyFagis/dropify#28]
I have tried these like so...

banner = $('#banner').dropify();

banner.destroy(); (does nothing)
banner.isDropified(); (says function doesn't exist)

I would like to destroy and re dropify a input each time an event happens.

**Comment by JeremyFagis** [comment]
Look at this [exemple](https://github.com/JeremyFagis/dropify/blob/master/index.html#L120-L129).
It seems you forgot something like this after the plugin init:  `banner = banner.data('dropify');`

**Comment by galipmedia** [comment]
Thanks for the quick reply!

**Comment by JeremyFagis** [comment]
:+1:
