### ISSUE TITLE
The selector ".dropify-font-empty" was not found

### ISSUE THREAD

**Issue by rfoel** [JeremyFagis/dropify#52]
So I was going to use the Dropify source sass and I get this error whenever I try to compile it. It turns out that the `.dropify-font-empty` is never declared in the source code, although it's being extended in the line 247. It can be easily fixed by commenting out this line or adding `!optional` at the end of it.

**Comment by maximecolin** [comment]
Same problem here. It prevents me from compiling my assets.

**Comment by maximecolin** [comment]
Thanks @JeremyFagis 👍
